"""
Export functionality for analysis results
"""

from datetime import datetime
from typing import Optional


def format_markdown_export(
    query: str,
    response: str,
    input_mode: str,
    language: str,
    model: str,
    timestamp: Optional[str] = None
) -> str:
    """Format analysis as markdown for export"""
    
    if not timestamp:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    markdown_content = f"""# MediVision AI - Medical Analysis Report

## Analysis Information
- **Date & Time**: {timestamp}
- **Model Used**: {model}
- **Language**: {language}
- **Input Mode**: {input_mode}

---

## Patient Input / Query

{query if query else "*No text input provided*"}

---

## AI Analysis

{response}

---

## Disclaimer

⚠️ **Important Notice**: This analysis is generated by an AI system and is intended for educational and informational purposes only. It should NOT be considered as professional medical advice, diagnosis, or treatment recommendation.

### Key Points:
- This is an AI-generated analysis, not a professional medical diagnosis
- Always consult with qualified healthcare professionals for medical concerns
- AI analysis may contain errors or incomplete information
- Emergency medical situations require immediate professional attention
- This tool is designed to assist, not replace, medical professionals

### Recommendations:
1. Share this analysis with your healthcare provider
2. Seek professional medical evaluation for any health concerns
3. Do not make medical decisions based solely on this AI analysis
4. In case of emergency, contact emergency services immediately

---

*Generated by MediVision AI - Diagnose with Clarity, Treat with Confidence*

*Report ID: {timestamp.replace(' ', '_').replace(':', '-')}*
"""
    
    return markdown_content


def get_export_filename(prefix: str = "MediVision_Analysis") -> str:
    """Generate filename for export"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"{prefix}_{timestamp}.md"


def create_download_button_config(content: str, filename: str) -> dict:
    """Create configuration for download button"""
    return {
        "data": content,
        "file_name": filename,
        "mime": "text/markdown"
    }
